# Generated by Django 4.1 on 2022-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
